base: /image

pipeline:
  publish:
    image: plugins/docker
    dockerfile: image/Dockerfile
    context: image/
    username: lobaroci
    repo: lobaro/dnsmasq-docker
    tags: [ latest ]
    secrets: [ docker_password ]
