version: '3'

services:
  dnsmasq:
    image: dnsmasq-docker:latest
    volumes:
      # Example to have a separate hosts_vpn file to resolve VPN hosts
      - ./cfg/dnsmasq.d:/etc/dnsmasq.d
      - ./cfg/hosts_vpn:/etc/hosts_vpn
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN