version: '3'

services:
  dnsmasq:
    image: lobaro/dnsmasq-docker:latest
    volumes:
      # Example to have a separate vpn file to resolve VPN hosts
      - ./cfg/dnsmasq.d:/etc/dnsmasq.d
      - ./cfg/hosts.d:/etc/hosts.d
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN